version: '2'
services:
    natchiyardemo4-app:
        image: natchiyardemo4
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://natchiyardemo4-mysql:3306/natchiyardemo4?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9000:9000
    natchiyardemo4-mysql:
        extends:
            file: mysql.yml
            service: natchiyardemo4-mysql
